src/src/src/Entity/Company.php
<?php

namespace App\Entity;

use App\Repository\CompanyRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CompanyRepository::class)
 */
class Company
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $comdescription;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $comlogo;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getComdescription(): ?string
    {
        return $this->comdescription;
    }

    public function setComdescription(string $comdescription): self
    {
        $this->comdescription = $comdescription;

        return $this;
    }

    public function getComlogo(): ?string
    {
        return $this->comlogo;
    }


    public function getComlogoUrl(): ?string
    {
        return 'assets/img/' . $this->comlogo;
    }

    public function setComlogo(?string $comlogo): self
    {
        $this->comlogo = $comlogo;

        return $this;
    }

    public function __toString(): string
    {
        return $this->name;
    }
}

src/src/src/Entity/Experience.php
<?php

namespace App\Entity;

use App\Repository\ExperienceRepository;
use App\Service\IOwner;
use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ExperienceRepository::class)
 */
class Experience implements IOwner
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $expname;
    
    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Please Enter atleast one name")
     */
    private $expdescription;

    /**
     * @ORM\Column(type="date")
     */
    private $expfrom;

    /**
     * @ORM\Column(type="date")
     */
    private $expto;

    /**
     * @ORM\Column(type="date")
     */
    private $createat;


    /**
     * @ORM\ManyToOne(targetEntity=Company::class,  cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $expcompany;

    /**
     * @ORM\ManyToOne(targetEntity=User::class,  inversedBy="experience")
     * @ORM\JoinColumn(nullable=false)
     */
    private $userid;

    public function __construct()
    {
        $this->createat = new DateTime();
        $this->expfrom = new DateTime();
        $this->expto = new DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getExpname(): ?string
    {
        return $this->expname;
    }

    public function setExpname(string $expname): self
    {
        $this->expname = $expname;

        return $this;
    }

    public function getExpdescription(): ?string
    {
        return $this->expdescription;
    }

    public function setExpdescription(string $expdescription): self
    {
        $this->expdescription = $expdescription;

        return $this;
    }

    public function getExpfrom(): ?\DateTimeInterface
    {
        return $this->expfrom;
    }

    public function setExpfrom(\DateTimeInterface $expfrom): self
    {
        $this->expfrom = $expfrom;

        return $this;
    }

    public function getExpto(): ?\DateTimeInterface
    {
        return $this->expto;
    }

    public function setExpto(\DateTimeInterface $expto): self
    {
        $this->expto = $expto;

        return $this;
    }

    public function getCreateat(): ?\DateTimeInterface
    {
        return $this->createat;
    }

    public function setCreateat(\DateTimeInterface $createat): self
    {
        $this->createat = $createat;

        return $this;
    }

    public function getExpCompany(): ?Company
    {
        return $this->expcompany;
    }

    public function setExpCompany(?Company $expcompany): self
    {
        $this->expcompany = $expcompany;

        return $this;
    }
 

    public function isOwner(User $user): ?bool
    {
          return $this->userid === $user;
    }

    /**
     * Set the value of userid
     *
     * @return  self
     */ 
    public function setUserid(?User $userid): self
    {
        $this->userid = $userid;

        return $this;
    }

    /**
     * Get the value of userid
     */ 
    public function getUserid()
    {
        return $this->userid;
    }
}

src/src/src/Form/ExperienceType.php
<?php

namespace App\Form;

use App\Entity\Company;
use App\Entity\Experience;
use DateTime;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ExperienceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('expcompany', EntityType::class, [
                'class' => Company::class,
                'choice_label' => function (Company $company) {
                    return $company->getName();
                },
                'label' => 'Company',
                'attr' => [
                    'class' => 'form-control',
                ],
                'choice_attr' => function ($choice, $key, $value) {
                    // adds a class like attending_yes, attending_no, etc
                    return ['class' => 'attending_' . strtolower($key)];
                },
            ])
            ->add('expname', TextType::class, [
                'label' => 'Job title'
            ])
            ->add('expdescription', TextareaType::class, [
                'label' => 'Job Experience',
                'attr' => ['rows' => 6]
            ])->add('expfrom', DateType::class, [
                'label' => 'Starts On',
                'data' => new DateTime()

            ])
            ->add('expto', DateType::class, [
                'label' => 'Finish On',
                'data' => new DateTime()
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Experience::class,

        ]);
    }
}

src/src/src/Controller/Experience/CompanyController.php
<?php

namespace App\Controller\Experience;

use App\Entity\Company;
use App\Form\CompanyType;
use App\Repository\CompanyRepository;
use App\Repository\ExperienceRepository;
use App\Service\FileUploader;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/company")
 * @IsGranted("ROLE_USER")
 */
class CompanyController extends AbstractController
{
    /**
     * @Route("/", name="app_company_index", methods={"GET"})
     */
    public function index(CompanyRepository $companyRepository, Request $request, PaginatorInterface $paginator, ExperienceRepository $experienceRepository): Response
    {

        $q = $request->query->get('q');
        $user_id = $this->getUser()->getId();

        $queryBuilder = $companyRepository->getCompanyByUser($q, $user_id, $experienceRepository);

        $paginator = $paginator->paginate(
            $queryBuilder,
            $request->query->getInt('page', 1),
            5
        );
        dump($paginator);
        return $this->render('company/index.html.twig', [
            'pagination' => $paginator,
        ]);
    }

    /**
     * @Route("/new", name="app_company_new", methods={"GET","POST"})
     */
    public function new(Request $request, FileUploader $fileUploader): Response
    {
        $company = new Company();
        $form = $this->createForm(CompanyType::class, $company);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $logo = $form->get('comlogo')->getData();
          
            if ($logo) {
                $fileName = $fileUploader->upload($logo);
                $company->setComlogo($fileName);
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($company);
                $entityManager->flush();
                return $this->redirectToRoute('app_company_index');
            }


            
        }

        return $this->render('company/new.html.twig', [
            'company' => $company,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_company_show", methods={"GET"})
     */
    public function show(Company $company): Response
    {
        return $this->render('company/show.html.twig', [
            'company' => $company,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_company_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Company $company, FileUploader $fileUploader): Response
    {
        $form = $this->createForm(CompanyType::class, $company);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $logo = $form->get('comlogo')->getData();
            if ($logo) {
                $fileName = $fileUploader->upload($logo);
                $company->setComlogo($fileName);
            }
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('app_company_index');
        }

        return $this->render('company/edit.html.twig', [
            'company' => $company,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_company_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Company $company): Response
    {
        if ($this->isCsrfTokenValid('delete' . $company->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($company);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_company_index');
    }
}

src/src/src/Controller/Experience/ExperienceController.php
<?php

namespace App\Controller\Experience;

use App\Entity\Company;
use App\Entity\Experience;
use App\Form\CompanyType;
use App\Form\ExperienceType;
use App\Repository\ExperienceRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/experience")
 * @IsGranted("ROLE_USER")
 */
class ExperienceController extends AbstractController
{

    /**
     * @Route("/", name="app_experience_index", methods={"GET"})
     */
    public function index(ExperienceRepository $experienceRepository, Request $request, PaginatorInterface $paginator): Response
    {

        $q = $request->query->get('q');
        $user_id = $this->getUser()->getId();

        $queryBuilder = $experienceRepository->getWithShareQuerybuilder($q, $user_id);

        $paginator = $paginator->paginate(
            $queryBuilder,
            $request->query->getInt('page', 1),
            5
        );
        return $this->render('experience/index.html.twig', [
            'pagination' => $paginator
        ]);
    }

    /**
     * @Route("/new", name="experience_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {

        $experience = new Experience();
        $experience->setUserid($this->getUser());

        $form = $this->createForm(ExperienceType::class, $experience);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($experience);
            $entityManager->flush();

            return $this->redirectToRoute('app_experience_index');
        }

        return $this->render('experience/new.html.twig', [
            'experience' => $experience,
            'form' => $form->createView()

        ]);
    }

    /**
     * @Route("/{id}", name="app_experience_show", methods={"GET"})
     * @IsGranted("OWNER", subject="experience")
     */
    public function show(Experience $experience): Response
    {
        return $this->render('experience/show.html.twig', [
            'experience' => $experience,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_experience_edit", methods={"GET","POST"})
     * @IsGranted("OWNER", subject="experience")
     */
    public function edit(Request $request, Experience $experience): Response
    {
        $form = $this->createForm(ExperienceType::class, $experience);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('app_experience_index');
        }

        return $this->render('experience/edit.html.twig', [
            'experience' => $experience,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_experience_delete", methods={"DELETE"})
     * @IsGranted("OWNER", subject="experience")
     */
    public function delete(Request $request, Experience $experience): Response
    {
        if ($this->isCsrfTokenValid('delete' . $experience->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($experience);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_experience_index');
    }
}

src/src/templates/experience/_delete_form.html.twig
<div class="col-sm-12 col-lg-12 text-right">
<form method="post" action="{{ path('app_experience_delete', {'id': experience.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ experience.id) }}">
    <button class="btn btn-danger text-right">Delete</button>
</form>
</div>

src/src/templates/experience/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-block btn-info">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

src/src/templates/experience/edit.html.twig
{% extends 'base/base.html.twig' %}
{% block title %}
	Edit Experience
{% endblock %}


{% block body %}
	<div class="container-fluid">
		<div class="row justify-content-center">
			<div class="col-sm-12 col-lg-6">
			<div class="text-center text-white">
				<h1>Edit Experience</h1>
			</div>
			

				{{ include('experience/_form.html.twig', {'button_label': 'Update'}) }}

				<a class="btn btn-warning" href="{{ path('app_experience_index') }}">back to list</a>

				{{ include('experience/_delete_form.html.twig') }}
			</div>

		</div>
	</div>


{% endblock %}

src/src/templates/experience/index.html.twig
{% extends 'base/base.html.twig' %}
{% block title %}
	Experience Table
{%
endblock %}
{% block body %}

	<div class="container-fluid main">
		<div class="row">
			{% for message in app.flashes('success') %}
				<div class="alert alert-success w-100">
					<h3>{{ message }}</h3>
				</div>
			{% endfor %}
			<div class="col-xs-7 col-sm-7 col-md-7 col-lg-12 text-left">
				<h3>Experience index</h3>
				<hr/>
			</div>
			<div class="row justify-content-center w-100 p-2">
				<div class="col-sm-4 col-md-4">
					<form class="row text-left">
						<input class="form-control col" value="{{ app.request.query.get('q') }}" name="q" type="search" placeholder="Search" aria-label="Search"/>
						<button class="col-lg-2 btn btn-outline-light my-2 my-sm-0" type="submit">
							Search
						</button>
					</form>
				</div>
			</div>
			<div class="col-lg-12 table-responsive">
				<table class="table table-striped text-white table-bordered">
					<thead class="thead-dark">
						<tr>
							<th>
								<div class="col-sm-2">#</div>
							</th>
							<th>Logo</th>
							<th>user</th>
							<th>Expname</th>
							<th>Expdescription</th>
							<th>Expfrom</th>
							<th>Expto</th>
							<th>Createat</th>
							<th>actions</th>
						</tr>
					</thead>
					<tbody>
						{% for experience in pagination %}
							<tr>
								<td>#</td>
								<td class="text-center">
									<a>
										<img src="{{ asset(experience.expcompany.comlogoUrl) }}" height="50">
									</a>
								</td>
								<td>{{ experience.userid }}</td>
								<td>{{ experience.expname }}</td>
								<td>{{ experience.expdescription | truncate }}</td>
								<td>
									{{ experience.expfrom ? experience.expfrom|date('Y-m-d') : '' }}
								</td>
								<td>{{ experience.expto ? experience.expto|date('Y-m-d') : '' }}</td>
								<td>
									{{ experience.createat ? experience.createat|date('Y-m-d') : '' }}
								</td>
								<td>
									<div class="row">
										<div class="col col-lg-6">
											<a class="btn btn-block btn-success" href="{{ path('app_experience_show', { id: experience.id }) }}">show</a>
										</div>
										<div class="col col-lg-6">
											<a class="btn btn-block btn-info" href="{{ path('app_experience_edit', { id: experience.id }) }}">edit</a>
										</div>
									</div>
								</td>
							</tr>
						{% else %}
							<tr>
								<td colspan="9">no records found</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>

			<div class="col">
				<div class="d-flex justify-content-end">
					{{ knp_pagination_render(pagination) }}

				</div>
				<div class="d-flex justify-content-center">
					<a class="btn btn-outline-light btn-block" href="{{ path('experience_new') }}">Create new</a>
				</div>
			</div>

		</div>

	</div>


{% endblock %}

src/src/templates/experience/new.html.twig
{% extends 'base/base.html.twig' %}
{% block title %}
	New Experience
{% endblock %}
{% block stylesheets %}
{{ parent() }}
{% endblock %}

{% block body %}
<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="col-sm-12 col-lg-6">
			<h1>Create new Experience</h1>

			{{ include("experience/_form.html.twig") }}

			<a class="btn btn-warning" href="{{ path('app_experience_index') }}">back to list</a>
		</div>

	</div>
</div>
	
 
{% endblock %}

src/src/templates/experience/show.html.twig
{% extends 'base/base.html.twig' %}
{% block title %}
	Experience

{% endblock %}


{% block body %}
	<div class="col-sm-6 col-lg-12">
		<h1>Experience</h1>

		<table class="table text-white">
			<tbody>
				<tr>
					<th>Id</th>
					<td>{{ experience.id }}</td>
				</tr>
				<tr>
					<th>Expname</th>
					<td>{{ experience.expname }}</td>
				</tr>
				<tr>
					<th>Expdescription</th>
					<td>{{ experience.expdescription }}</td>
				</tr>
				<tr>
					<th>Expfrom</th>
					<td>{{ experience.expfrom ? experience.expfrom|date('Y-m-d') : '' }}</td>
				</tr>
				<tr>
					<th>Expto</th>
					<td>{{ experience.expto ? experience.expto|date('Y-m-d') : '' }}</td>
				</tr>
				<tr>
					<th>Createat</th>
					<td>{{ experience.createat ? experience.createat|date('Y-m-d') : '' }}</td>
				</tr>
			</tbody>
		</table>
		<div class="row">
			<div class="col-sm-12 col-lg-6">
				<a class="btn btn-warning btn-block" href="{{ path('app_experience_index') }}">back to list</a>
			</div>
			<div class="col-sm-12 col-lg-6">
				<a class="btn btn-info btn-block" href="{{ path('app_experience_edit', {'id': experience.id}) }}">edit</a>
			</div>
		</div>
		<div class="p-3">
			{{ include('experience/_delete_form.html.twig') }}
		</div>


	</div>

{% endblock %}